name: Preprocessing Automation

on:
  push:
    paths:
      - 'preprocessing/**'
      - 'employee_data_raw.csv'

permissions:
  contents: write

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pandas scikit-learn

      - name: Run automate_Ilhaam_Akmal_Abdjul.py
        run: |
          python preprocessing/automate_Ilhaam_Akmal_Abdjul.py \
            --input employee_data_raw.csv \
            --output preprocessing/employee_data_preprocessing.csv

      - name: Commit updated preprocessed data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add preprocessing/employee_data_preprocessing.csv
          git commit -m "Update preprocessed data via GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}